name: Deploy Development
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm ci
      - run: npm test
      - run: npm run build
      - run: npm run lint
      - run: CF_API_TOKEN=${{ secrets.CF_API_TOKEN }} npm run deploy
      - name: Lighthouse Check
        id: lighthouseCheck
        uses: foo-software/lighthouse-check-action@v1
        with:
          urls: "https://development.whentho.xyz"
      - name: Check Lighthouse Results
        uses: foo-software/lighthouse-check-status-action@master
        with:
          lighthouseCheckResults: ${{ steps.lighthouseCheck.outputs.lighthouseCheckResults }}
          minAccessibilityScore: "60"
          minBestPracticesScore: "95"
          minPerformanceScore: "95"
          minProgressiveWebAppScore: "10"
          minSeoScore: "50"
